version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_USER=api
      - MONGODB_PASSWORD=api
      - MONGODB_DATABASE=api
  api:
    build: .
    ports:
      - '50080:80'
    volumes:
      - 'api_data:/bitnami/api'
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
volumes:
  mongodb_data:
    driver: local
  api_data:
    driver: local
